name: Trigger frappe_docker Build

on:
  push:
    branches:
      - version-15

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FRAPPE_DOCKER_PAT }}
          repository: wkoubaa1986/frappe_docker
          event-type: woocommerce_fusion_updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
